name: RSS Sync
on:
  push:
    branches: [main]
  schedule:
    - cron: "*/15 * * * *" # æ¯ 15 åˆ†é’Ÿè‡ªåŠ¨è¿è¡Œ
  workflow_dispatch: # æ”¯æŒæ‰‹åŠ¨è§¦å‘

jobs:
  rss-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch äººæ°‘ç½‘-æ”¿æ²»
        continue-on-error: true
        uses: Promptly-Technologies-LLC/rss-fetch-action@v2
        with:
          feed_url: "https://plink.anyfeeder.com/people/politics"
          file_path: "feeds/people-politics.json"

      - name: Fetch 36æ°ª
        continue-on-error: true
        uses: Promptly-Technologies-LLC/rss-fetch-action@v2
        with:
          feed_url: "https://plink.anyfeeder.com/36kr/news/latest"
          file_path: "feeds/36kr.json"

      - name: Fetch ITä¹‹å®¶
        continue-on-error: true
        uses: Promptly-Technologies-LLC/rss-fetch-action@v2
        with:
          feed_url: "https://plink.anyfeeder.com/ithome/rss"
          file_path: "feeds/ithome.json"

      - name: Auto-Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ğŸ¤– è‡ªåŠ¨æ›´æ–° RSS"
          file_pattern: "feeds/*"
